/*
****************************************************************************
*  Copyright (c) 2025,  Skyline Communications NV  All Rights Reserved.    *
****************************************************************************

By using this script, you expressly agree with the usage terms and
conditions set out below.
This script and all related materials are protected by copyrights and
other intellectual property rights that exclusively belong
to Skyline Communications.

A user license granted for this script is strictly for personal use only.
This script may not be used in any way by anyone without the prior
written consent of Skyline Communications. Any sublicensing of this
script is forbidden.

Any modifications to this script by the user are only allowed for
personal use and within the intended purpose of the script,
and will remain the sole responsibility of the user.
Skyline Communications will not be responsible for any damages or
malfunctions whatsoever of the script resulting from a modification
or adaptation by the user.

The content of this script is confidential information.
The user hereby agrees to keep this confidential information strictly
secret and confidential and not to disclose or reveal it, in whole
or in part, directly or indirectly to any person, entity, organization
or administration without the prior written consent of
Skyline Communications.

Any inquiries can be addressed to:

	Skyline Communications NV
	Ambachtenstraat 33
	B-8870 Izegem
	Belgium
	Tel.	: +32 51 31 35 69
	Fax.	: +32 51 31 01 29
	E-mail	: info@skyline.be
	Web		: www.skyline.be
	Contact	: Ben Vandenberghe

****************************************************************************
Revision History:

DATE		VERSION		AUTHOR			COMMENTS

13/01/2025	1.0.0.1		AMA, Skyline	Initial version
****************************************************************************
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Generated.SDM.Ticketing.Models
{
    using System;
    using System.Linq;

    using Skyline.DataMiner.Analytics.GenericInterface;
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using Skyline.DataMiner.SDM.Ticketing.Models;

    [GQIMetaData(Name = "Get TicketTypes")]
    public sealed class GetTicketTypes : IGQIDataSource, IGQIOnInit
    {
        private GQIDMS _dms;
        private TicketTypeStorageProvider _ticketTypeHelper;
        public OnInitOutputArgs OnInit(OnInitInputArgs args)
        {
            _dms = args.DMS;
            _ticketTypeHelper = new TicketTypeStorageProvider(_dms.GetConnection());
            return default;
        }

        public GQIColumn[] GetColumns()
        {
            return new GQIColumn[] { new GQIStringColumn("Guid"), new GQIStringColumn("ID"), new GQIStringColumn("Name") };
        }

        public GQIPage GetNextPage(GetNextPageInputArgs args)
        {
            return new GQIPage(_ticketTypeHelper.Read(new TRUEFilterElement<TicketType>()).Select(item => new GQIRow(new GQICell[] { new GQICell { Value = Convert.ToString(item.Guid) }, new GQICell { Value = item.ID }, new GQICell { Value = item.Name }, })).ToArray());
        }
    }
}